package com.bhupinder.notification.dto;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * NotificationPayload is a record, so equals/hashCode/accessors are
 * generated by the compiler - these tests aren't testing Java's record
 * mechanics. They exist to lock in the FIELD SHAPE this payload commits to,
 * since both NotificationPublisher (Redis) and the STOMP wire format
 * (browser clients) depend on this exact shape. A future accidental field
 * rename or type change here would break wire compatibility silently without
 * a test like this catching it immediately.
 */
class NotificationPayloadTest {

    @Test
    void recordExposesAllThreeFieldsCorrectly() {
        NotificationPayload payload = new NotificationPayload("user-1", "hello", 1700000000000L);

        assertThat(payload.topic()).isEqualTo("user-1");
        assertThat(payload.message()).isEqualTo("hello");
        assertThat(payload.publishedAtEpochMillis()).isEqualTo(1700000000000L);
    }

    @Test
    void recordsWithSameValuesAreEqual() {
        NotificationPayload a = new NotificationPayload("user-1", "hello", 123L);
        NotificationPayload b = new NotificationPayload("user-1", "hello", 123L);

        assertThat(a).isEqualTo(b);
        assertThat(a.hashCode()).isEqualTo(b.hashCode());
    }

    @Test
    void recordsWithDifferentTimestampsAreNotEqual() {
        NotificationPayload a = new NotificationPayload("user-1", "hello", 123L);
        NotificationPayload b = new NotificationPayload("user-1", "hello", 456L);

        assertThat(a).isNotEqualTo(b);
    }
}
